var d = new Date();

module.exports.goodReplies = function(game, author) {
let goodcomment = [
  "Very good video! 10/10",
  "This makes me happy inside",
  "This video is out of this world.",
  "Can you like my comment!",
  "Will you marry me",
  "Cool vid, lol",
  "Like if your heart is big",
  `**${game}** videos are amazing!`,
  "U are so good at the game",
  "This video is so mythical",
  "Like if my mom is gay",
  "Hey guys my mom just died can you give me l8es please!!!!!!",
  "Hey, can you play this game called **Fortnite**? Btw im 10",
  "can u smell my feet",
    "are u a weeb",
    "Do u like music",
  `${author.username} is the best utuber!`,
  `Like if you have a crush on ${author.username}`,
  `Nice vid!`,
  `YES! **${game}** VIDEOS!`,
  "<held for review>",
    "Like if you're a boomer",
    "Like if you have STD",
    "Like if you have coronavirus",
    "OWOWOWOWOWOWOWOWOWOWO U SO KUTE PLS NOTICE ME SENPAI",
    "penis",
    "i just farted",
    "Nice video! Subscribe to me please.",
    "Sub for sub??",
  "I love it! You should really post more...",
  `I really like **${game}** videos! Please post more of it!`,
  `Damn, this channel ${author.username} is underrated`,
  "Very litty.",
  "Nice! When will you post more?",
  "Good video.",
  `Great job, ${author.username}!`,
  `Better than my bros. Bravo`,
  `${author.username}, you're a pretty talented youtuber. Keep it up :D`,
  "Pretty cool video!",
  "Oh nice.",
  "THIS VIDEO IS SO FUNNY LMAO 10/10",
  "😂😂😂so funny! Subbed 👍",
  "This guy is funny as hell dude",
  "This game is the best!",
  "NICE!!!",
  "OMG THIS CHANNEL IS SO COOL!",
  "nice video.",
  "cool. :3",
  ":3",
  "OwO you look cute",
  `${author.username}, you should play this game called **Terraria**, it's pretty good i heard.`,
 `${author.username}, you should play this game called **Stardew Valley**, it's pretty good i heard.`,
  `${author.username}, you heard of this shitty gamed called **Fortnite**? Please don't tell me you play it. I'll unsub you...`,
  `${author.username} is cool`,
  `lolololololol!`,
  `hahahah! so funny!`,
  `owo`,
  `uwu`,
  `hey im 10 and i like your channel`,
  `dude give me a shoutout`,
  "boy boy boy",
  "girl girl girl",
  `Fun fact: Your mom gay. HAHHAHAhHHAHHA IM SO FUNNY`,
  "yeet",
  "cum on carpet",
  "baby",
  "i like Metallica",
  "i like Nirvana",
  "aaww you're cute",
  "hi",
  "jajajajaja",
  "yum",
  "cool",
  "nice vid",
  `Like if you're watching in ${d.getFullYear()}`,
  `Like if im gay`,
  `Like if you don't wanna like`,
  `hey my sister just died can you give me likes plssss cause im so saddd!`,
  `Who's watching in ${d.getFullYear()}`,
  `${author.username}, you really helped me through my hard times watching your videos... I just wanted to say thank you so much!`,
  `Dude, how do you get ${game}? TELL ME PLEASE PLEASE PLEASE! I SUBBED!`,
  "Please upload more :D",
  "Dude... And that channel **T-Series** has way more subs than yours... Smh",
  "Nice, nice.",
  "Coolio",
  ":)",
  ":D",
  "Very good video."
 ]
return goodcomment;
}
module.exports.badReplies = function (game, user) {
  let badcomment = [
  "wtf is this lmao",
  "vErY gOoD vIdEo iKr",
  "this kid sounds like some dog getting choked by his owner",
  "Dude, you sound like a dumbass.",
  "ew",
  ":(",
  "D:",
  "I didn't know you were this bad at the game, play something else...",
  "Dude, you suck.",
  "LMFAO! You call that skills?",
  "lmfao... are you 12?",
  "very edgy",
  "This video is really mediocre.",
  `Ewwww, ${game} videos? DISLIKE!`,
  "Ima pretend i never saw this video.",
  "Dude, your videos need a lot of improvements.",
  "Bullshit.",
  "this video sucks! it worse than poopy diaper it should get pooped in the street cause your diaper so poopy that you never change it!",
  "I remember making these types videos, lmao. So cringy.",
  "Cringe.",
  "cringe",
  "wtf is this",
  "Lmao your voice sounds like 2",
  "Very edgy.",
  "Very cringy.",
  "ew",
  `Like if you think ${user.username} is a dumbass`,
  `nice grammar you have there, ${user.username}`,
      "ur mom gay",
      "kid u suck play **fortnite** it bestest game",
      "fuck you fuck you fuck you fuck you",
      "SOMEONE PLEASE EXPOSE THIS GUY",
      "fuck you asian sounding cunt",
      "this video is poop",
    "this video sucks",
    "poop",
    "Even my farts are funnier than this video",
      "I'd rather watch **T-Series**",
      "my dog's better than you",
      "suck my small dick",
        "duuude u suck!!!",
      "u poop at the game i want to say bad word but i am 9 so my mommy no let me but you very poop poop poop",
      "Sexy condoms",
      "ur mum gay lol",
    "ur iq is so bad",
    "ur iq is below bedrock",
    "ok",
    "no one cares",
    "ur irrelevant",
    "uber",
    "my dog just died and its a better person than you. NOW GIVE ME LIKESSSSSSS",
    "youre so poop that my dog poop is better OOOOOHHH ROASTEDDDDDDD",
    "u suck at this game!",
    "**Fortnite** is best! this game sucks!!! im 9 btw",
    "**Roblox** bestest why you play this poopy diaper game! Unsubscriptioned!",
    "this video sux",
    "u look so ugly m8",
    "ewwwwwwwww",
    "This crap is so bad my dog wont even eat it OOOOOOOOO ROASTEDDDD ",
    "ur mom probably looks like d ifell tower "
    ]
  return badcomment;
  
};

//lol 👌im
//iminavcandimgettingsuggestions